# plugins:
# https://github.com/iberianpig/fusuma-plugin-sendkey

hold:
  1:
    sendkey: "VOLUMEDOWN"
  2:
    sendkey: "VOLUMEUP"
  3:
    sendkey: "F5"
  4:
    sendkey: "LEFTCTRL+LEFTSHIFT+T"

threshold:
  hold: 0.3
